### Introducción a Numpy - Librería de Python para realizar cálculos numéricos en Python

#### Primero tenemos que importar la libreria usando `import`. Para evitar escribir `numpy` cada vez usamos una función que nos permite asignarle un alias `as`:

In [4]:
import numpy as np

#### Ahora tenemos acceso a todas las funciones disponibles en  `numpy` tipeando `np.name_of_function`.  Por ejemplo, la operación `1 + 1` en Python se puede realizar en `numpy` de la siguente manera:

In [5]:
np.add(1,1)

2

##### Aunque no parezca muy útil, estas operaciones pueden ser mucho más rápidas en `numpy` que en Python cuando se usan muchos números. 

#### Para acceder a la documentación que explica cómo se usa una función, cuáles son sus parámetros de entrada y de salida, hay que poner `Shift+Tab` después del nombre de la función

In [6]:
np.add

<ufunc 'add'>

#### Por default se muestra el resultado de la función u operación al ejecutar la celda 

In [7]:
np.add(2,3)

5

#### Si se va a reutilizar el resultado después se puede asignar el resultado a una variable

In [8]:
a = np.add(2,3)

#### El contenido de esta variable se puede mostrar en cualquier momento tipieando el nombre de la variable en una nueva celda

In [9]:
a

5

#### Uno de los conceptos más poderosos en numpy son los `arrays`  (o arreglos) que son equivalentes a listas de números. Para declarar un array de numpy:

In [10]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### La mayoría de las funciones y operaciones definidas en numpy pueden aplicarse a arrays. Por ejemplo, con la operación de recién:

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

np.add(arr1, arr2)

array([ 4,  6,  8, 10])

#### Ejercicio: Definimos un array con un elemento más (arr3) y vean qué pasa si queremos hacer la suma arr1+arr3. Normalmente los arrays tienene que tener las mismas dimensiones 

In [12]:
arr3= np.array([1,2,3,4])


In [13]:
arr1+arr3

array([2, 4, 6, 8])

#### Ejercicio: qué pasa si hacemos arr1+1?

In [19]:
arr1 + 1


array([2, 3, 4, 5])

#### Los arreglos se pueden recortar. Nos podemos quedar con subsets del array usando la siguiente notación`[start:end:stride]`. Veamos un ejemplo:

In [20]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(arr[5])
print(arr[5:])
print(arr[:5])
print(arr[::2])

5
[ 5  6  7  8  9 10 11 12 13 14 15]
[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14]


##### Experimenten jugando con los índices para entender el significado de start, end y stride. Qué pasa si no especifican el start? Qué valor usa numpy como default? NOTA: el primer índice en numpy es `0`, la misma convención se usa en las listas de Python.

#### Los arreglos de Numpy arrays pueden tener múltiples dimensiones. Por ejemplo, para definir un `column` array: 

In [20]:
np.array([[1,2,3,4,5,6,7,8,9]])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### Para visualizar la forma o dimensiones del arreglo de numpy hay que agregar el sufijo`.shape`

In [21]:
print(np.array([1,2,3,4,5,6,7,8,9]).shape)
print(np.array([[1,2,3,4,5,6,7,8,9]]).shape)

(9,)
(1, 9)


##### Para definir una rreglo de dos dimensiones:

In [22]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
print(np.array([[1,2,3,4],[5,6,7,8]]).shape)

(2, 4)


#### Se pueden reordenar los datos del arreglo a diferentes formas con la función `reshape`:

In [28]:
np.array([1,2,3,4,5,6,7,8]).reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Definan un arreglo de 3 dimensiones con la forma  (5,3,3)

In [39]:
aa = np.array([5,3,3])

#### Creen otro y usen la función de numpy para sumar ambos arrays:

In [82]:
bb = np.array([1,1,1])
cc = aa + bb
print(cc)

[6 4 4]


### Cómo extraer items que satisfacen una cierta condición en un array 1D?

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 


####  Extraer los números impares de arr 

In [24]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [66]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [49]:
x < 3  # less than


array([ True,  True, False, False, False])


### Operador :	Función equivalente		
* "!="	:	np.not_equal
* "<"	:	np.less		
* "<=" :	np.less_equal
* ">"	:	np.greater	
* ">=" :	np.greater_equal

In [30]:
rng = np.random.RandomState(0)
x = rng.randint(2, size=(3, 4))
x

array([[0, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0]])

In [33]:
x < 0


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
# Cuántos valores son menores a  6?
np.count_nonzero(x < 6)

12

In [36]:
# Cuántos valores son menores a  6 en cada fila?
np.sum(x < 6, axis=1)

array([4, 4, 4])

In [54]:
# Son todos los valores en cada fila menores a 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

### Mas ejercicios
https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html
    