### Repaso Numpy

Mirar los videos que están en la plataforma de Acámica, los ejemplos de clase y la clase_03_01_numpy y tratar de resolver los siguientes ejercicios y preguntas


In [8]:
import numpy as np

A partir de una lista podemos crear un arreglo de numpy

In [29]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [4]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Cosas que no se podían hacer con las listas ahora sí se pueden:

In [5]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [6]:
arreglo + 1

array([1, 2, 3, 4, 5, 6])

In [7]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
arreglo**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

In [10]:
print(lista[0])
print(arreglo[0])

#lista + 1 NO arreglo + 1 si
#filas x columnas
#(n,)=tiene m cantidades de filas y 1 columna
#(n,1)= tiene n cantidades de filas con 2 columnas
#(1,n)= tiene 1 fila  y n columnas

0
0


**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [19]:
asd = np.array(range(0,10))
print(asd)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
asdf = np.array(range(0,9*100,9))
print(asdf)

[  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153
 162 171 180 189 198 207 216 225 234 243 252 261 270 279 288 297 306 315
 324 333 342 351 360 369 378 387 396 405 414 423 432 441 450 459 468 477
 486 495 504 513 522 531 540 549 558 567 576 585 594 603 612 621 630 639
 648 657 666 675 684 693 702 711 720 729 738 747 756 765 774 783 792 801
 810 819 828 837 846 855 864 873 882 891]


**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50. Notar que se puede hacer en una sola línea. Comparar con el extra del ejercicio 1 de Python.

In [28]:
asdfg = np.array(np.array(range(0,100,10)))
c = np.array(asdfg < 50)
print(asdfg[c])
print(c)

[ 0 10 20 30 40]
[ True  True  True  True  True False False False False False]


In [10]:
a = np.arange(10,100)
'''Pista'''
for i in a:
    if i>50
mask = [True, False, True, False]
print(a[mask])

IndentationError: expected an indented block (<ipython-input-10-a96c27ab80f7>, line 4)

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/


# more and more

In [4]:
import numpy as np

In [9]:
#Create a 1D array of numbers from 0 to 9
aa = np.array(range(1,10))
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#matrix 3x3 all true
aaa = np.full((3,3),True, dtype=bool)
aaa

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
#Extract all odd numbers from arrr
arrr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
aaaa = arrr[arrr%2!=0]
aaaa

array([1, 3, 5, 7, 9])

In [22]:
#Replace all odd numbers in arr with -1
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr1 % 2 == 1, -1, arr1)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [36]:
arr2 = np.array(range(0,10))
arr2.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])